spring.application.name=ultary-api
# 포트 설정
server.port=9378
# 부트재시작없이 동적소스 reload
spring.devtools.livereload.enabled=true
spring.freemarker.cache=false
spring.thymeleaf.cache=false
# DB(JDBC) - MySQL
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://127.0.0.1:3306/ultary-api?serverTimezone=UTC
#spring.datasource.username=95hanho
#spring.datasource.password=1q2w3e4r!!
# DB(JDBC) - MariaDB
#spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
# DB(JDBC) - MariaDB p6spy 사용 시 필수
spring.datasource.driver-class-name=com.p6spy.engine.spy.P6SpyDriver
#spring.datasource.url=jdbc:mariadb://localhost:3306/ehfqntuqntu
spring.datasource.url=jdbc:p6spy:mariadb://203.245.44.21:3306/ehfqntuqntu
# DB 기본값
spring.datasource.username=
spring.datasource.password=
#
spring.datasource.dbcp2.default-auto-commit=false
#
spring.mvc.hiddenmethod.filter.enabled=true
spring.mvc.problemdetails.enabled=true
# 헤더사이즈 제한
server.max-http-request-header-size=400000
# 마이바티스 설정
mybatis.configuration.jdbc-type-for-null=null
#mybatis.config-location=classpath:mybatis/mybatis-config.xml
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.mapper-locations=classpath:mappers/*.xml
mybatis.type-aliases-package=me._hanho
#.ultary-api.model,me._hanho.ultary-api.dto
# 파일 관련 설정
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB
#spring.servlet.multipart.location=D:/files/ultary-api
spring.servlet.multipart.location=/home/hosting_users/ehfqntuqntu/files/ultary-api
# MyBatis SQL 로그
logging.level.org.mybatis=DEBUG
logging.level.org.apache.ibatis=DEBUG
logging.level.java.sql=DEBUG
mybatis.configuration.log-impl=org.apache.ibatis.logging.slf4j.Slf4jImpl
logging.level.com.p6spy=INFO
# Mapper 클래스 로그 (네가 만든 AuthMapper 패키지 기준)
#logging.level.me._hanho.ultary-api.mapper=DEBUG
