spring:
  config:
    activate:
      on-profile: prod

  # ==============================
  # DB 설정 (MariaDB + p6spy) - Prod (cafe24)
  # ==============================
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver

    # cafe24 운영 DB
    url: jdbc:mariadb://localhost:3306/ehfqntuqntu

    # DB 계정 정보 (환경변수로 주입)
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

    dbcp2:
      default-auto-commit: false

  # ==============================
  # 파일 업로드 경로 - Prod (cafe24)
  # ==============================
  servlet:
    multipart:
      location: ${UPLOAD_DIR:/home/hosting_users/ehfqntuqntu/files/ultary-api}
